language: ruby
rvm:
- 2.3.0
script: npm install -g yarn
deploy:
  provider: heroku
  api_key:
    secure: mQwidCkDSOwWNBSV98ZxE023MGSngz07VheF2hAkpXuPlkLU0qIhvfomizIHwjDZK5f57PSQk5FmKgscB1lqiUHFZ7N9QTliKi8A1mP0My0DXfreM1T5GiMfl9JegibKmCStfyxUEqBbt9DGAuybuuSaFIBT8rv+9BcL62GPEsJXtbiMAM3Jbt3RQ7PH7ruWaVHYdRVTo0IvPD7uxXSoOen+VIngj1bknxY8iAiB7D0wmjFVku+BXfU3oFgmVaQCfgXvZj5HLKMwW1EBr8jKfQenSV901hAvmaoRLfWlly5U/i7U+CpZmfClZHXO7JNzPxhd3EmHF90czW8BcWZwT+c62/B2/NAvu/dnxD2WMjBonfuapNwcyzjqsD3cOihdu6Ro4xVfwbOFQPsVYKIrvrxDsqyVZJGeX3Z2+eACtDXrBM1jX96eR08sBAjXX1lvAtfokkS++PEU9yLEcuoNF14IoZCjgQjYt3T2Fjis+4ipLgHzFpN9tiF0UF9CkD4KYS+n17siWVLvSJirhnampbqSRXYluxgD7MzIPsPwIbjDMGFutX3rwMSB2LdaVZNnambfNoe7GAb/Hl3HjViSAoWJPyIxfaY8LC/N0s1dA3TpTYa1YsEaRNQngO5tJE47JEgQTySGpF5D0MrdeyfHbd/0QZJZdADF2x0LY/CrOmU=
  app:
    master: alldid-staging
    prod: alldid
  on:
    repo: dben89x/alldid
  skip_cleanup: true
notifications:
  email: false
